adaptlearning/adapt-contrib-mcq

bower.json, package.json, properties.schema
=> Adds support for _supportedLayout

less/mcq.less
Removed border from MCQ item for use within the theme version 2
=> CSS theme update

example.json, properties.schema
"_shouldDisplayAttempts" required by all questions. JSON copied from contrib-textInput.
=> Add _shouldDisplayAttempts

less/mcq.less
=> Hide input checkbox

js/adapt-contrib-mcq.js
https://adaptlearning.atlassian.net/browse/ABU-690
=> Added SCORM interactions support.

js/adapt-contrib-mcq.js
so as to make adding randomisation to GMCQ (see [GCMQ issue 83](https://github.com/adaptlearning/adapt-contrib-gmcq/issues/83))  nice and DRY
also remove comments that were simply restating what was obviously happening in the code, re-write/add comments where helpful
=> refactor randomisation code out into separate function

templates/mcq.hbs
Similar issue to https://github.com/adaptlearning/adapt-contrib-gmcq/pull/90 - not full disabling on revisit.
=> Added disabled attribute on input upon revisit

properties.schema
to reflect that `_isRandom` is optional and false by default and that `_incorrect.notFinal` and `_partlyCorrect` feedbacks are optional
=> amends to properties.schema

js/adapt-contrib-mcq.js
Added length check on items array before starting for loop. 
This fixes a JS error which prevented the course page from loading.
=> Defensive programming

README.md, bower.json, properties.schema
This makes more sense as there are typically more false options than true.
=> Changed _shouldBeSelected default to false

properties.schema
Schema change so it is easier for course creators to understand what each attribute does.
=> Schema - Changed Items to Answers

js/mcqModel.js, js/mcqView.js
Also moved getResponseType() and getResponse() functions from view to model.
=> Added getInteractionObject() to model

properties.schema
update to option specific feedback text area. now has text editor options.
fixes https://github.com/adaptlearning/adapt_framework/issues/2029
=> MCQ option specific feedback text area fix

js/mcqModel.js
fix odd indentation, add missing semi-colon
=> ensure feedback title works with option-specific feedback

js/mcqModel.js
Fixes https://github.com/adaptlearning/adapt_framework/issues/2067.
=> Restore compatibility with framework v2.2

properties.schema
[#2165](https://github.com/adaptlearning/adapt_framework/issues/2165)
* Updated label to be easier to digest
=> accessibility: issue/#2165 updated component description

js/mcqModel.js
Finishes resolving https://github.com/adaptlearning/adapt-contrib-mcq/pull/144#issue-205186822.
=> Return early if no feedback

js/mcqModel.js, js/mcqView.js, templates/mcq.hbs
[#2084](https://github.com/adaptlearning/adapt_framework/issues/2084)
* Removed component description
[#1837](https://github.com/adaptlearning/adapt_framework/issues/1837)
* Allows checkbox selection at selection limit
[#2088](https://github.com/adaptlearning/adapt_framework/issues/2088)
* Alerts twice on selection
[#2085](https://github.com/adaptlearning/adapt_framework/issues/2085)
* Ensure focus stays on selection
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
=> accessibility: issue/#2084, issue/#1837, issue/#2088, issue/#2085

js/adapt-contrib-mcq.js, js/mcqView.js, less/mcq.less, templates/mcq.hbs
MCQ converted to use 2 spaces for indentation.
=> update to use 2 spaces for indentation

properties.schema
see https://github.com/adaptlearning/adapt_framework/issues/2365
=> amend help text for answer-specific feedback

js/mcqView.js
https://github.com/adaptlearning/adapt_framework/issues/2750
=> lookup inside the current scope

properties.schema
as per https://github.com/adaptlearning/adapt_framework/issues/2543
=> improve ARIA region label

less/mcq.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891
=> Less tidy up

properties.schema
all the functionality for this is handled via itemsQuestionModel.js - so all that's needed here is the addition of the 'globals'.
part of https://github.com/adaptlearning/adapt_framework/issues/2942
=> add 'ARIA answer' text

templates/mcq.hbs
part of https://github.com/adaptlearning/adapt_framework/issues/3142
* `aria-labelledby` to `component__inner`
Use with framework [pr#3143](https://github.com/adaptlearning/adapt_framework/pull/3143)
=> issue/3142 Added aria-labelledby to component__inner

properties.schema
https://github.com/adaptlearning/adapt_framework/issues/3148
* schema support for `_isPartlyCorrect`
Requires https://github.com/adaptlearning/adapt_framework/pull/3149
=> issue/3148 Added support for item _isPartlyCorrect

README.md, example.json, properties.schema
Part of https://github.com/adaptlearning/adapt_framework/issues/3163
* `_hasItemScoring` support
Required https://github.com/adaptlearning/adapt_framework/pull/3172
=> issue/3163 Added _hasItemScoring

templates/mcq.jsx
fixes #164 
* Marking now displays correctly
=> issue/6 Fixed correctness display

less/mcq.less, templates/mcq.jsx
Resolves https://github.com/adaptlearning/adapt-contrib-mcq/issues/171
* Converted mcq naming so each item is treated as a block within BEM
=> bem naming amends

templates/mcq.jsx
fixes #175 
* Added readOnly property
=> issue/175 Fixed missing readOnly warning

less/mcq.less, templates/mcq.jsx
fixes #179 
* Converted divs to spans as div elements are not allowed in label elements
=> issue/179 Switched divs to span inside label

README.md, properties.schema, schema/component.schema.json
fixes: #184
* ariaQuestion not available in AAT
=> Fix: ariaQuestion added to readme and schema.

example.json, properties.schema, schema/component.schema.json
#187 
* default instruction text provided
=> New: Provide default instruction text (fixes #187)

properties.schema, schema/component.schema.json
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Adds ariaQuestion field to modern schema standards
[//]: # (List appropriate steps for testing if needed)
1. Install RP and test in AAT
=> Fix: Update Schema for ariaQuestion (fixes #190)

templates/mcq.jsx
fixes #186 
* All items to be selected after reset
=> Fix: Reset item selection (fixes #186)

js/McqView.js
fixes #199 
* Focus change, in selection, on radio buttons, with a screen reader, now updates ui
=> Fix: Focus change in selection on radio buttons updates ui

test/e2e/mcq.cy.js
=> Chore: e2e tests on mcq component (Issue/218)

test/e2e/mcq.cy.js
=> Fix: Moved striphtml function outside loop (fixes #221)

migrations/v2.js, migrations/v3.js, migrations/v4.js, migrations/v7.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#232 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* migration scripts added to the repo (fixes #232)
=> Fix: migration scripts added to the repo (fixes #232)

bower.json, package-lock.json, package.json
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#235 
Part of - https://github.com/adaptlearning/adapt_framework/issues/3698
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #235)
=> Update: package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #235)
